### ISSUE TITLE
Settings not applied correctly

### ISSUE THREAD

**Issue by MadeByMike** [IdeaSpaceVR/aframe-particle-system-component#13]
The following example should be a perfectly legitimate velocity value setting:

`<a-entity position="0 0 0" particle-system="preset: snow; velocityValue:0 1 0"></a-entity>`

However this doesn't work, if any 0 value is set, default settings will be applied. This because of the following code: 

```
velocityValue: (this.data.velocityValue.x!==0&&this.data.velocityValue.y!==0&&this.data.velocityValue.z!==0?this.data.velocityValue:{x: 1, y: 8, z: 1}),
```

This is the same for all presets and properties with vec3 values. 

I know it sucks to raise an issue and not a PR for something that has been identified like this. I'll raise a PR if I get time but noting it so I don't forget.

**Comment by chriscar** [comment]
Thanks for reporting!

**Comment by andreyrd** [comment]
This still does not solve the issue of setting a vector to exactly "0 0 0".
This component should be using the robust defaults system found in the aframe component system: https://aframe.io/docs/0.8.0/introduction/writing-a-component.html#defining-properties-with-the-schema

**Comment by andreyrd** [comment]
Opened a new issue for "0 0 0" specifically! #41
