### ISSUE TITLE
Garbage Collection Issues

### ISSUE THREAD

**Issue by pappapete** [IdeaSpaceVR/aframe-particle-system-component#14]
I'm using the component to add a particle emitter to represent an explosion on a collision between two objects. At the point of the collision, a new element is created and the particle-system attribute added to create the particle emitter element.

The duration of the emitting of the particles is 0.25 seconds, then after two seconds the element with the particle system is removed. I've noticed that after after multiple collisions/explosions, the memory usage is going up and up, even though the elements have been removed. Is there a way to handle the garbage collection?

**Comment by chriscar** [comment]
This a-frame component is just a thin wrapper around https://github.com/squarefeet/ShaderParticleEngine . Please have a look at this particle engine repository.
