### ISSUE TITLE
Issue with 0.3.0 cursor component

### ISSUE THREAD

**Issue by manojkota** [IdeaSpaceVR/aframe-particle-system-component#16]
Hi,

If you reference A-frame version >0.3.0 without cursor scene is working fine. With the cursor, the screen is kind of struck and laggy.

**Comment by chriscar** [comment]
Which device? Do you have a codepen for that?

**Comment by manojkota** [comment]
I don't have a codepen for this. Just add <a-cursor></a-cursor> to your camera entity. Then you can see the issue. It's happening across all devices.

**Comment by chriscar** [comment]
Please have a look with A-frame version 0.4.0.

**Comment by manojkota** [comment]
I have checked it with the new version. Now the issue is with Texture. It couldn't able to find the particle texture.

**Comment by chriscar** [comment]
I don't understand. If you use one of the presets (default, dust, snow, rain), they do not show up?

**Comment by zchen39** [comment]
I am experiencing the same problem with cursor. I am using 0.5.0 and whenever the cursor intersects with the source of the particles, it becomes super laggy.

**Comment by freemanon** [comment]
Same issue

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.5.0/components/raycaster.html#whitelisting-entities-to-test-for-intersection

**Comment by tyherox** [comment]
Hi, this problem seems to be still evident in the current build. 

I made a short-term fix by providing object selectors on my raycaster. Works like a charm now!

**Comment by ngokevin** [comment]
Always specify `objects`, always.
