### ISSUE TITLE
Example page is down, publish to GitHub pages + add link in GH description

### ISSUE THREAD

**Issue by ngokevin** [IdeaSpaceVR/aframe-particle-system-component#19]
If you add me as GitHub collaborator + npm owner, I can help maintain if you want.

**Comment by weddingdj** [comment]
The examples are back, and I added you as a collaborator. Thanks!

**Comment by ngokevin** [comment]
Thanks! Can I also be added as an Admin, to do stuff like add a GitHub description or configure GitHub pages?

**Comment by ngokevin** [comment]
Also as npm owner ```npm owner add ngokevin``` :)

**Comment by weddingdj** [comment]
Ok I added you as npm owner as well... may the force be with you :-)

**Comment by weddingdj** [comment]
I updated the examples with a-frame 0.5.0 and npm published it. Feel free to add/remove things.

**Comment by ngokevin** [comment]
Thanks! Loving the component (https://aframe-5000.glitch.me)

**Comment by weddingdj** [comment]
I saw that tweet ;-) glitch looks promising too!
