### ISSUE TITLE
Publish the code for the rain/dust/etc examples/

### ISSUE THREAD

**Issue by ngokevin** [IdeaSpaceVR/aframe-particle-system-component#2]
Will be very helpful!

**Comment by chriscar** [comment]
The configuration parameters for rain/dust/etc presets?

**Comment by ngokevin** [comment]
Just for those examples at the bottom, would be nice to have an easy place to view source https://github.com/IdeaSpaceVR/aframe-particle-system-component#examples

**Comment by chriscar** [comment]
Added examples to repository and added links to the repository.
