### ISSUE TITLE
Camera breaks page

### ISSUE THREAD

**Issue by stevel4857** [IdeaSpaceVR/aframe-particle-system-component#24]
I added the particle system into my project to create snow. I set up a camera to do an animation from the camera as a fly through but that broke everything. The page wouldn't load. I see that I can WASD and have a camera. Have you seen this before and is there a work around? I did try to find reference to a camera in the code but couldn't. 
http://www.cablecenter.org/vr/snow-test/

**Comment by weddingdj** [comment]
Do you have an example of the broken fly through?

**Comment by stevel4857** [comment]
Basically it's a standard aframe camera added to the,scene in the link. It
breaks then

**Comment by weddingdj** [comment]
I have not seen that before. So if you add a-camera to the scene the page never stops loading, or is there an error in the console? Is the page working if you remove the particle system?

**Comment by stevel4857** [comment]
I can check the console but it starts to load and when it hits the particle it stops loading. It must crash because I need to restart my nightly browser when I do this. I had a-camera in it and cursor. I removed the cursor code and it syill happened. Then I removed any WASD and other controls in the camera and it still did this. I didn't check the console because I'm a bit of a newbie in this so I never thought to do that.

**Comment by stevel4857** [comment]
OK. I recreated the page and added the a-camera back in and it works. My guess is that the browser cache had some weird issue and created the error. At any rate, today it;s completely fine. I have other issues like sound pooling with a looping audio as an error in the console but and scaling issues but no crash anymore. Sorry.
