### ISSUE TITLE
unpkg.com host link is broken

### ISSUE THREAD

**Issue by drubio1989** [IdeaSpaceVR/aframe-particle-system-component#25]
While trying to follow the instructions for "Browser Installation", I saw that the link to aframe-particle system is broken?

https://unpkg.com/aframe-particle-system@1.0.x/dist/aframe-particle-system-component.min.js

**Comment by weddingdj** [comment]
In the meantime, you could use https://raw.githubusercontent.com/IdeaSpaceVR/aframe-particle-system-component/master/dist/aframe-particle-system-component.min.js or you download the component.

**Comment by drubio1989** [comment]
Thanks @weddingdj for providing a work around for my problem. However, I'm experiencing a different problem when installing this library that I'm hoping you could provide a solution. I am using Aframe 0.5.0 and have followed the instructions for npm installation.

When I attempt to render a basic component such as the dust component, it fails to render at all. For expediency's sake, I've attached an image of my html file.
![screen shot 2017-05-18 at 9 23 08 pm](https://cloud.githubusercontent.com/assets/6200151/26229526/54226fe4-3c10-11e7-9110-3eef99e4bca7.png)

I opened the inspector and found that the particle-system component is not registered for some reason but I am able to add it through the inspector. Additionally, when I add it through the aframe inspector it does not seem to populate the component with the provided library defaults. An example is particleCount field. If possible could you please confirm?

**Comment by ngokevin** [comment]
You did not include the component

**Comment by drubio1989** [comment]
Thank you for the speedy reply @ngokevin. You'll have to bear with me as I'm new to aframe and VR in general but what do you mean I forgot the component? Isn't this piece of html the component?

<a-entity position="0 2.25 -15" particle-system="preset: dust"></a-entity>

**Comment by ngokevin** [comment]
On the Web, you include JS files as a `<script>` tag in order to use it. The particle-system component is a library you need to include. In your code, you only included A-Frame.

**Comment by drubio1989** [comment]
But I already installed it with npm as detailed in the instructions @weddingdj at the top of this thread also said to either use the link as a script tag or to simply download it.

**Comment by weddingdj** [comment]
But in your example code you do not include the component script. You have to add this statement below the A-Frame script tag:

`<script src="https://raw.githubusercontent.com/IdeaSpaceVR/aframe-particle-system-component/master/dist/aframe-particle-system-component.min.js"></script>`

**Comment by ngokevin** [comment]
So npm installation steps require a bundler like Webpack or Browserify to use, and then you still have to include it.

**Comment by drubio1989** [comment]
I'm trying to meet you guys half way as best as I can. I'm using the aframe boilerplate [https://github.com/aframevr/aframe-boilerplate](url) by default and I'm trying to figure out if I already have webpack or browserify with the boilerplate. Do I need to install webpack and browserify separately?

Additionally, I have my branch here https://github.com/drubio1989/aframe-boilerplate/tree/dust . If any of you guys have a moment to check it out, I'd appreciate it. Just to reiterate and be clear about my problem, I definitely have the package installed and I can eventually see the particle variations only by using the inspector tool. When I have that entity, nothing shows up but by using the inspector to add the particle-system component it works. But I can't see it when I go to scene mode.

**Comment by ngokevin** [comment]
Put this in your JS head `<script src="https://unpkg.com/aframe-particle-system-component@1.0.10/dist/aframe-particle-system-component.min.js"></script>`, that's all

**Comment by drubio1989** [comment]
There we go, got it! Thanks a bunch for the help I really appreciated. Now I'm back on track.
