### ISSUE TITLE
Throws error when fog is active

### ISSUE THREAD

**Issue by awesomephant** [IdeaSpaceVR/aframe-particle-system-component#26]
I was trying to build a scene on the master branch of aframe using both fog and a particle system. This seems to break the particle component, throwing this error:

```
THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: fogDepth
```

[Test case](https://codepen.io/maxakohler/pen/gRgZZP)

This doesn't happen on on aframe 0.5.0.

**Comment by weddingdj** [comment]
Could you file an issue in the a-frame repository? Maybe there has been a change related to the fog.

**Comment by kfarr** [comment]
After @weddingdj [PR adding `THREE.ShaderChunk.fog_pars_vertex`](https://github.com/IdeaSpaceVR/aframe-particle-system-component/pull/28/files) per advice from [this issue on aframe core](https://github.com/aframevr/aframe/issues/2897) using aframe 0.7 I am now seeing a different error when using this particle system component along with fog:

> In three.js:18003: THREE.WebGLProgram: shader error:  0
> gl.VALIDATE_STATUS false gl.getProgramInfoLog invalid shaders
> ERROR: 0:335: 'mvPosition' : undeclared identifier
> ERROR: 0:335: 'z' :  field selection requires structure or vector on left hand side

(In addition to the unhelpful `THREE.WebGLShader: Shader couldn't compile.`)

**Comment by lukecarbis** [comment]
The same happens with the aframe environment component (https://github.com/feiss/aframe-environment-component) enabled.

**Comment by kfarr** [comment]
@lukecarbis some presets on environment component include fog by default (hence this error), you can still use environment component if you disable fog by setting `fog` parameter to `0`

**Comment by lukecarbis** [comment]
@kfarr Yes, can confirm. Definitely a problem related to fog. Another example here: https://github.com/lukecarbis/drone-attack

**Comment by ngokevin** [comment]
Happens to me as well. Don't know if you need to update the SPE library to adjust.

**Comment by vesper8** [comment]
does anyone know how to detect if fog is active ?
