### ISSUE TITLE
position of particle emitter is offset when not at 0,0,0

### ISSUE THREAD

**Issue by joshmarinacci** [IdeaSpaceVR/aframe-particle-system-component#29]
It appears that the position of the emitter is scaled by a factor of two. When I create the following scene we should see the particles coming from the center of the sphere. In fact it is 5 units behind the sphere.  

    <a-scene>
      <a-entity position="0 1.25 -5" particle-system="color: #EF0000,#44CC00"></a-entity>
      <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"></a-sphere>
    </a-scene>

**Comment by kfarr** [comment]
Can close issue? this looks complete and I tested, working

**Comment by joshmarinacci** [comment]
Yep. Thanks!
