### ISSUE TITLE
Fire preset

### ISSUE THREAD

**Issue by sidthekidder** [IdeaSpaceVR/aframe-particle-system-component#3]
Really useful repo!
I wanted a fire preset so I tried to create one similar to the default preset - this is what it looks like:
![fireanim](https://cloud.githubusercontent.com/assets/3611800/16174186/7f2bbb38-35d5-11e6-88bf-8db7d959c7b5.gif)

Properties: maxAge: 0.05; size: 0.5; rotationAngle: -30; color: #FFFF00; texture: ./images/fire.png

The fire.png texture has a transparent background, but the color property is messing it up - either the default (purple) or any other color value washes out the texture. Can the color property be disabled, opacity set to 0 or something? Or if you know any better properties for fire.

**Comment by chriscar** [comment]
A fire preset is a good idea.

Yes, there is a opacity setting but I am not exposing it through the component. I will add it.

**Comment by chriscar** [comment]
I added the opacity parameter. Let me know if it works for your fire preset.

**Comment by sidthekidder** [comment]
Thanks for the help! I tried it out, the opacity is actually applied on the texture as well, so it fades out the image as well as the color. Maybe I was thinking more of the alpha in rgba() type effect, anyway I am trying a different way to have a fire effect, with no texture/images.
