### ISSUE TITLE
Doesn't work with version 6 or 7. 

### ISSUE THREAD

**Issue by stevel4857** [IdeaSpaceVR/aframe-particle-system-component#33]
Just that. I need functionality for version 6 and also need snow. But, can't have both it seems.

**Comment by weddingdj** [comment]
A-Frame 0.7.0 should work. There is a snow preset: https://ideaspacevr.github.io/aframe-particle-system-component/examples/snow/

**Comment by stevel4857** [comment]
Yes. It was adding fog depth into the scene. It worked in 5 but not after.
I guess some change was made. I took fog out and it works now.
