### ISSUE TITLE
Cannot set vectors to "0 0 0"

### ISSUE THREAD

**Issue by andreyrd** [IdeaSpaceVR/aframe-particle-system-component#41]
The way the current defaults system works is it will fall back to the default value unless at least one of the x,y,z values is !== 0.

For example, the default value for accelerationValue is "0 -10 0". You can't set the accelerationValue to "0 0 0" because it does not find a nonzero x,y,z value, so it falls back to "0 -10 0".

A-frame already provides a way of providing default values for schema properties, and it overrides the default if any value for the property is specified, doesn't just check if one of the values is not 0. https://aframe.io/docs/0.8.0/introduction/writing-a-component.html#defining-properties-with-the-schema

I can open a PR for this if I get the thumbs up, because it would probably be a significant change and a major version bump, since I'm sure people have had to work around the existing default value system. I've had to set my acceleration values to tiny values like 0.00001 to work around it.

**Comment by weddingdj** [comment]
Ok, your idea sounds good to me if all presets will still work.

**Comment by Cheaterman** [comment]
Bit of a heads up there - this isn't fixed. :-(
