### ISSUE TITLE
Particle system not working with environment preset and/or fog

### ISSUE THREAD

**Issue by FireDragonGameStudio** [IdeaSpaceVR/aframe-particle-system-component#55]
**Description:**

- A-Frame Version: >=1.0.0
- Platform / Device: Firefox
- Reproducible Code Snippet or URL:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello environment!</title>
    <meta charset="utf-8">
    <meta name="description" content="Simple • A-Frame" />
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-particle-system-component@1.0.9/dist/aframe-particle-system-component.min.js"></script>
    <script src="https://unpkg.com/aframe-environment-component/dist/aframe-environment-component.min.js"></script>
  </head>  
  <body>
    <a-scene id="scene" environment="preset: forest">
        <a-entity particle-system="preset: rain"></a-entity>
    </a-scene>
  </body>
</html>
```

Sry for the crosspost ([https://github.com/aframevr/aframe/issues/4446](https://github.com/aframevr/aframe/issues/4446)) but I currently have the problem, that the environment presets of the [https://unpkg.com/aframe-environment-component/dist/aframe-environment-component.min.js](https://unpkg.com/aframe-environment-component/dist/aframe-environment-component.min.js) package and the particle system are not working with Aframe >=1.0.0 The same error appears, when fog is used instead of the environment preset within the scene. I know that there was an similar error a few years ago (#46, #26) , but it appears to happen again.

I guess @kfarr already found a solution, pls refer to [this commit](https://github.com/roskelld/aframe-particle-system-component/commit/2b8ce2730dcbb465b342d0c4832feabbdcaa539f).

When using aframe 0.9.0 at least the camera movement is working, although the browser inspector throws the same error -> 

THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog Must have a compiled vertex shader attached. 
THREE.WebGLShader: gl.getShaderInfoLog() vertex
ERROR: 0:364: 'mvPosition' : undeclared identifier
ERROR: 0:364: 'z' :  field selection requires structure or vector on left hand side1: precision highp float;
2: precision highp int;
3: #define HIGH_PRECISION
4: #define SHADER_NAME ShaderMaterial
5: #define HAS_PERSPECTIVE true
6: #define COLORIZE true
7: #define VALUE_OVER_LIFETIME_LENGTH 4
8: #define SHOULD_ROTATE_PARTICLES true
9: #define VERTEX_TEXTURES
10: #define GAMMA_FACTOR 2
11: #define MAX_BONES 0
12: #define USE_FOG
13: #define BONE_TEXTURE
14: uniform mat4 modelMatrix;
15: uniform mat4 modelViewMatrix;
16: uniform mat4 projectionMatrix;
17: uniform mat4 viewMatrix;
18: uniform mat3 normalMatrix;
19: uniform vec3 cameraPosition;
20: uniform bool isOrthographic;
21: #ifdef USE_INSTANCING
22:  attribute mat4 instanceMatrix;
23: #endif
24: attribute vec3 position;
25: attribute vec3 normal;
26: attribute vec2 uv;
27: #ifdef USE_TANGENT
28: 	attribute vec4 tangent;
29: #endif
30: …
 <empty string> three.js:18243:12

TypeError: e.fogColor.value is null three.js:25942:3

core:a-node:error Failure loading node:   TypeError: "this.environmentData.lightPosition is undefined"
    Aframe 10
browser.js:111:32

Best regards :)

**Comment by denisbabineau** [comment]
@FireDragonGameStudio we ran into this same issue with fog, you can test out the fix I submitted in 
 https://github.com/IdeaSpaceVR/aframe-particle-system-component/pull/56 from this temporary branch:

`npm install git+https://github.com/denisbabineau/aframe-particle-system-component.git#issue-55-fog-dist`

**Comment by FireDragonGameStudio** [comment]
@denisbabineau Thx for the link and sry for the late reply. Although the shader error is gone when using your fix, there is still the error ```TypeError: e.fogColor.value is null``` left. Do you know why this occours?
