### ISSUE TITLE
Have presets load images from CDN

### ISSUE THREAD

**Issue by ngokevin** [IdeaSpaceVR/aframe-particle-system-component#6]
It took me a couple tries until I read the line in the docs to package the images. 

Though maybe consider packaging the images with Webpack into the JS bundle (convert to data URI). Can help if you think it's a good idea.

**Comment by chriscar** [comment]
It's a good idea, please do.

**Comment by ngokevin** [comment]
I started trying this, but figured it'd be easier to just point to the image files hosted somewhere. And then developers can pull it down and reference locally if they want too.

**Comment by chriscar** [comment]
What about pointing to the images on github, eg. https://raw.githubusercontent.com/IdeaSpaceVR/aframe-particle-system-component/master/dist/images/cloud.png ?

**Comment by ngokevin** [comment]
Yeah, that'd work, just make sure it's CORsable (e.g., use `rawgit.com`)

**Comment by chriscar** [comment]
rawgit.com is CORSable, tested it, published a new release, npm as well.

**Comment by ngokevin** [comment]
awesome! Now we can include it in `aframe-registry`, then add particle systems from the `aframe-inspector`. Before we couldn't because you needed the image files on a relative path.
