### ISSUE TITLE
Fragment Shader related crash, A-Frame 1.1.0 & 1.2.0

### ISSUE THREAD

**Issue by vulture-boy** [IdeaSpaceVR/aframe-particle-system-component#62]
When running the latest build of the particle system as part of an A-Frame 1.1.0 or 1.2.0 project, the fragment system seems to encounter an error.

```
THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog Fragment shader is not compiled.
THREE.WebGLShader: gl.getShaderInfoLog() fragment
ERROR: 0:247: 'texture' : function name expected
ERROR: 0:247: '=' : dimension mismatch
ERROR: 0:247: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'
1: #version 300 es
2: #define varying in
3: out highp vec4 pc_fragColor;
4: #define gl_FragColor pc_fragColor
5: #define gl_FragDepthEXT gl_FragDepth
6: #define texture2D texture
[...]
258: 	#endif
259: 	gl_FragColor.rgb = mix( gl_FragColor.rgb, fogColor, fogFactor );
260: #endif
261: }
[...]
```

Call tree for three.js seems to include this, but otherwise no other a-frame scripts
```
value | @ | a-scene.js:798
```

We don't have a complicated particle system setup, just the Snow preset
https://ideaspacevr.github.io/aframe-particle-system-component/examples/snow/
which works just fine in this example. Removing the particle system removes the issue, as does downgrading it.

The script is loaded with this:
```
    <script src="https://unpkg.com/aframe-particle-system-component@1.0.x/dist/aframe-particle-system-component.min.js"></script>
```

Any idea what might be causing this?

**Comment by amaclean199** [comment]
Also wondering about this!

**Comment by JaimieVos** [comment]
Having the same issue here!

**Comment by gftruj** [comment]
Hi, 
I think the npm package is not updated so the link from the docs doesn't work:    
`https://unpkg.com/aframe-particle-system-component@1.0.x/dist/aframe-particle-system-component.min.js`

If you refer directly to the distribution via gh (or just host the file from the `dist` folder`):
 `https://ideaspacevr.github.io/aframe-particle-system-component/dist/aframe-particle-system-component.j`

It's working with `a-frame` 1.3.0 https://jsfiddle.net/gftruj/ok3bpc40/1/

**Comment by diarmidmackenzie** [comment]
@weddingdj - it looks like the NPM package for this is not up to date (and doesn't work).

I've seen tis come up in a few communities & cause a lot of frustration.  Are you able to look at this?

**Comment by vulture-boy** [comment]
> Hi, I think the npm package is not updated so the link from the docs doesn't work: `https://unpkg.com/aframe-particle-system-component@1.0.x/dist/aframe-particle-system-component.min.js`
> 
> If you refer directly to the distribution via gh (or just host the file from the _dist_ folder) : `https://ideaspacevr.github.io/aframe-particle-system-component/dist/aframe-particle-system-component.js`
> 
> It's working with `a-frame` 1.3.0 https://jsfiddle.net/gftruj/ok3bpc40/1/

Thanks for this, the distro link does indeed work for our system! Glad to be able to use particles again!
https://ocadu-open-webxr.glitch.me/gallery_template.html

Worth mentioning that the 'rain' preset seems to fail in our instance?
