### ISSUE TITLE
question: how can I do runtime alteration of parameter?

### ISSUE THREAD

**Issue by tinchoz49** [IdeaSpaceVR/aframe-particle-system-component#7]
Hi,

First let me tell you that I really like this component, it works great.

and here is my question:

I want to change the colors of the particles in runtime is there a way to do that? I try using ```setAttribute('particle-system', 'color'...``` but the particles system is restarted using this option.

Thanks!

**Comment by tinchoz49** [comment]
Sorry, i didn't see that this project is based on the squarefeet/ShaderParticleEngine. I know how can I change the values in that project and is the same here.

I'm going to close the issue.

**Comment by clemsos** [comment]
Hey, could you explain how you did this ? 
I can not figure out how to access the shader from Aframe...

**Comment by tinchoz49** [comment]
hi @clemsos ! you can check my example to understand it: https://github.com/tinchoz49/vr-synthesis-osc

**Comment by clemsos** [comment]
Thanks @tinchoz49 ! 
So you basically call the particle component using JS, right ? https://github.com/tinchoz49/vr-synthesis-osc/blob/cc7b30d0362933d85877e58437c5fdd874f6f6cd/client/src/vr/explosion.js#L73

Any idea if I can access the component using  DOM  selection or Three.js object  ?
