### ISSUE TITLE
Document development/build steps

### ISSUE THREAD

**Issue by ngokevin** [IdeaSpaceVR/aframe-particle-system-component#9]
Most npm commands were stripped out and examples are hard-coded to use rawgit.com. Can you add some instructions on how you develop?

**Comment by chriscar** [comment]
The preset texture image paths are hardcoded (if you use a preset like rain, dust, etc.), unless you provide your own texture, then the preset textures are overwritten (see https://github.com/IdeaSpaceVR/aframe-particle-system-component#usage-examples). This is comfortable as the people can just use preset: rain and it just works, without worrying about images and paths (that's what you suggested previously).

My "development process" is very simple: after using webpack to generate the dist, I just use npm publish. I have a particle test page and I manually copy the dist files over for debugging. Not a very optimised process but it works for now.

**Comment by chriscar** [comment]
Btw, any recommendations on how to setup a better process / best practices are very much welcome.
